### ISSUE TITLE
How to actually use icon packs...?

### ISSUE THREAD

**Issue by bclaymiles** [jamie-mh/AuthenticatorProIcons#1]
I note the newish functionality to add icon packs. I dutifully downloaded the icon packs via the application, but I'm unclear how one actually uses them. After downloading them, then returning to the 'icon packs' menu item, it's simply the same, instructing the user to download icon packs.

?

**Comment by jamie-mh** [comment]
You need to click the "Add" button in the bottom right of the icon packs screen. You can then select the icon pack from your downloads folder to import it.
