### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by alabotski** [jamie-mh/AuthenticatorProIcons#2]
Hi can you  add new icons

- Mail.ru
- Yandex.ru

To [simple-icons-white.iconpack](https://github.com/jamie-mh/AuthenticatorProIcons/releases/download/2023-10-21/simple-icons-white.iconpack)

**Comment by jamie-mh** [comment]
As the name suggests, the icon pack is created from the [Simple Icons](https://github.com/simple-icons/simple-icons) project. You need to create your request there instead.
